forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Forum

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /entrepot

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit
employe:
    resource: "@EmployeBundle/Resources/config/routing.yml"
    prefix:   /employe
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User
entrepot_mobile:
    resource: "@EntrepotMobileBundle/Resources/config/routing.yml"
    prefix:   /entrepotmobile
commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

tache:
    resource: "@TacheBundle/Resources/config/routing.yml"
    prefix:   /tache
recrutement:
    resource: "@RecrutementBundle/Resources/config/routing.yml"
    prefix:   /recrutement
conge:
    resource: "@CongeBundle/Resources/config/routing.yml"
    prefix:   /conge
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications