produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit
employe:
    resource: "@EmployeBundle/Resources/config/routing.yml"
    prefix:   /employe
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

