<?php

namespace TacheBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{

    public function Recherche($commentaire)
    {
        $query = $this->getEntityManager()->createQuery("Select p FROM TacheBundle\Entity\Tache p WHERE p.commentaire=:commentaire")
                        ->setParameter('commentaire',$commentaire);
                        return $query->getResult();
    }
    public function TriParCommentaire()
    {

        $query = $this->getEntityManager()->createQuery("Select p FROM TacheBundle\Entity\Tache p ORDER BY p.commentaire");
        return $query->getResult();

    }


    public function TacheEmploye($id)
    {
        $query = $this->getEntityManager()->createQuery("SELECT t from TacheBundle\Entity\Tache t WHERE t.idEmploye=:id")
        ->setParameter('id',$id);
        return $query->getResult();
    }


    public function RechercheEmpTache($prenom)
    {
    $query = $this->getEntityManager()->createQuery("Select p FROM TacheBundle\Entity\Tache p WHERE p.idEmploye=(Select u.id FROM EmployeBundle\Entity\Employe u WHERE u.prenom=:prenom)")
        ->setParameter('prenom',$prenom);
    return $query->getResult();
    }







}

