<?php

namespace CommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{


    public function getCommande()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT c.id as id , c.etat as etat , u.username as nom ,  u.telephone as telephone  ,  u.email as email , c.date as date , c.total as total  from UserBundle:User u JOIN CommandeBundle:Commande c WITH c.iduser = u.id ");
        return $query->getResult();

    }
}
