<?php

namespace CommandeBundle\Repository;

/**
 * LigneCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLigneCommande($idCommande )
    {

        $query = $this->createQueryBuilder('l')
            ->where('l.idCommande = :idCommande')
            ->setParameters(array(
                    'idCommande'=>$idCommande
                )
            )
            ->getQuery();
        return $query->getResult();
    }
}
