user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
user:
    path:     /loginMobile/{username}/{password}
    defaults: { _controller: UserBundle:Default:loginMobile }
