tache_homepage:
    path:     /
    defaults: { _controller: TacheBundle:Default:index }
tache_ajout:
    path:     /ajoutTache
    defaults: { _controller: TacheBundle:Default:ajoutTache }
tache_modifier:
    path:     /modifierTache/{id}
    defaults: { _controller: TacheBundle:Default:modifierTache }
tache_afficher:
    path:     /listTaches
    defaults: { _controller: TacheBundle:Default:listTaches }
tache_supprimer:
    path:     /supprimerTache/{id}
    defaults: { _controller: TacheBundle:Default:supprimerTache }
tache_recherche:
    path:     /rechercheTache
    defaults: { _controller: TacheBundle:Default:rechercheTache }
tache_tri:
    path:     /triTache
    defaults: { _controller: TacheBundle:Default:afficheTacheTri }
afficher_recherche:
    path:     /afficherRecherche
    defaults: { _controller: TacheBundle:Default:afficherRecherche }
employeTache:
    path:     /employetache/{id}
    defaults: { _controller: TacheBundle:Default:afficheTacheEmploye}
tacheEmploye:
    path:     /tacheEmploye/{id}
    defaults: { _controller: TacheBundle:Default:updateTache}
allTaches:
    path:     /allTaches
    defaults: { _controller: TacheBundle:Default:allTaches}
tache_new:
    path:     /newTache
    defaults: { _controller: TacheBundle:Default:newTache}
delete_tache:
    path:     /removeTache
    defaults: { _controller: TacheBundle:Default:deleteTache}
remuneration:
    path:     /remunererEmploye
    defaults: { _controller: TacheBundle:Default:remunererEmployes}
superviser:
    path:     /superviserEmployes
    defaults: { _controller: TacheBundle:Default:superviserEmployes}
raterTache:
    path:     /raterTache
    defaults: { _controller: TacheBundle:Default:raterTache}
getEmpTache:
    path:     /getEmpTache
    defaults: { _controller: TacheBundle:Default:tachEmploy}
validate:
    path:     /validerTache
    defaults: { _controller: TacheBundle:Default:ValiderTache}