<?php

namespace EmployeBundle\Repository;

/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends \Doctrine\ORM\EntityRepository
{
    public function Recherche($nom,$prenom, $poste)
    {

        $query = $this->getEntityManager()->createQuery("Select p FROM EmployeBundle\Entity\Employe p WHERE p.nom=:nom AND p.prenom=:prenom AND p.poste=:poste")
            ->setParameter('nom',$nom)
            ->setParameter('prenom',$prenom)
            ->setParameter('poste',$poste);
        return $query->getResult();

    }

    public function TriPlusCherMoinsCher()
    {
        $query = $this->getEntityManager()->createQuery("Select p FROM EmployeBundle\Entity\Employe p ORDER BY p.salaire");

        return $query->getResult();
    }

    public function TriParPrenom()
    {
        $query = $this->getEntityManager()->createQuery("Select p FROM EmployeBundle\Entity\Employe p ORDER BY p.prenom");

        return $query->getResult();
    }


    public function RechercheEmp($id)
    {

        $query = $this->getEntityManager()->createQuery("Select p FROM EmployeBundle\Entity\Employe p WHERE p.id=:id")
            ->setParameter('id',$id);
        return $query->getResult();

    }
    public function RechercheEmpUser($prenom)
    {

        $query = $this->getEntityManager()->createQuery("Select p FROM EmployeBundle\Entity\Employe p WHERE p.prenom=:prenom")
            ->setParameter('prenom',$prenom);
        return $query->getOneOrNullResult();

    }




}
