<?php

namespace EmployeBundle\Repository;

/**
 * superviserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class superviserRepository extends \Doctrine\ORM\EntityRepository
{
    public function SuperviserEmploye($id)
    {
        $query = $this->getEntityManager()->createQuery("SELECT t from EmployeBundle\Entity\superviser t WHERE t.idEmploye=:id")
            ->setParameter('id',$id);
             return $query->getResult();
    }
}
