<?php

namespace ForumBundle\Repository;

/**
 * ratingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingRepository extends \Doctrine\ORM\EntityRepository
{
}
