<?php

namespace CongeBundle\Repository;

/**
 * CongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongeRepository extends \Doctrine\ORM\EntityRepository
{
    public function Recherche($nbJours,$attachement)
    {

        $query = $this->getEntityManager()->createQuery("Select p FROM CongeBundle\Entity\Conge p WHERE p.nbJours=:nbJours AND p.attachement=:attachement")
                      ->setParameter('nbJours',$nbJours)
                      ->setParameter('attachement',$attachement);
        return $query->getResult();

    }
    public function TriParNbJours()
    {
        $query = $this->getEntityManager()->createQuery("Select p FROM CongeBundle\Entity\Conge p ORDER BY p.nbJours");
        return $query->getResult();

    }
    public function TriParAttachement()
    {
        $query = $this->getEntityManager()->createQuery("Select p FROM CongeBundle\Entity\Conge p ORDER BY p.attachement");
        return $query->getResult();

    }
}
